networks:
  dev:

volumes:
  news_aggregator_data:

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - news_backend
      - news_frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev
  news_db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - news_aggregator_data:/var/lib/postgresql/data
    networks:
      - dev
  news_backend:
    build: ./news_aggregator/
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - news_db
    networks:
      - dev
  news_frontend:
    build: ./news_aggregator_frontend/
    ports:
      - "3000:3000"
    networks:
      - dev
